- name: Configurer et déployer Apache
  hosts: nodes
  become: yes
  tasks:
    - name: Installer le package Apache
      ansible.builint.package:
        name: apache2
        state: present

    - name: Démarrer le service Apache
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Copier le fichier de configuration
      ansible.builtin.copy:
        src: files/apache.conf
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Créer un dossier pour l'app
      ansible.builtin.file:
        path: /var/www/html/app
        state: directory
        mode: '0755'

    - name: Copier le fichier html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/app/index.html

