---
# tasks file for roles/webserver
- name: Démarrer le service apache2
  ansible.builtin.service:
    name: apache2
    state: started
  

- name: Copier le fichier de configuration
  ansible.builtin.template:
    src: apache2.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache2

- name: Créer un répertoire pour la page statique
  ansible.builtin.file:
    path: /var/www/html/app
    state: directory
    mode: '0755'
  
- name: Copier le fichier HTML 
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/app/index.html







  